#!/usr/bin/env bash
# vendor_ptz_agent.sh — COPY the parts of ptz-agent this repo needs into
# vendor/ptz_agent/, so jetson-ptz-agent-graph is self-contained (no sibling
# ../ptz-agent required at runtime).
#
# This only ever COPIES — it never moves or modifies the source ptz-agent.
#
# Usage:
#   bash scripts/vendor_ptz_agent.sh                 # auto-find ../ptz-agent
#   bash scripts/vendor_ptz_agent.sh /path/to/ptz-agent
#
# Re-run any time the upstream ptz-agent changes to refresh the vendored copy.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SRC="${1:-}"
if [[ -z "$SRC" ]]; then
  for cand in "$ROOT/../ptz-agent" "${PTZ_AGENT_ROOT:-}" "$HOME/ptz-agent"; do
    if [[ -n "${cand:-}" && -f "$cand/tools/ptz_facade.py" ]]; then
      SRC="$cand"; break
    fi
  done
fi

if [[ -z "$SRC" || ! -f "$SRC/tools/ptz_facade.py" ]]; then
  echo "ERROR: could not find a ptz-agent source (needs tools/ptz_facade.py)." >&2
  echo "       Pass it explicitly: bash scripts/vendor_ptz_agent.sh /path/to/ptz-agent" >&2
  exit 1
fi
SRC="$(cd "$SRC" && pwd)"

DEST="$ROOT/vendor/ptz_agent"
echo "==> Vendoring ptz-agent runtime"
echo "    source: $SRC"
echo "    dest:   $DEST"
mkdir -p "$DEST"

# Copy only the runtime subset the gateway bridges to. Exclude caches and
# transient state. rsync if available (clean mirror), else cp fallback.
EXCLUDES=( "__pycache__" "*.pyc" ".DS_Store" "scratchpads" "logs" )

copy_dir() {
  local name="$1"
  if [[ ! -e "$SRC/$name" ]]; then
    echo "    (skip $name — not present in source)"
    return
  fi
  if command -v rsync >/dev/null 2>&1; then
    local args=(-a --delete)
    for e in "${EXCLUDES[@]}"; do args+=(--exclude "$e"); done
    rsync "${args[@]}" "$SRC/$name/" "$DEST/$name/"
  else
    rm -rf "${DEST:?}/$name"
    cp -R "$SRC/$name" "$DEST/$name"
    find "$DEST/$name" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
    find "$DEST/$name" -name '*.pyc' -delete 2>/dev/null || true
  fi
  echo "    copied $name/"
}

copy_dir tools
copy_dir msa
copy_dir sensors

# Panorama for the simulated PTZ backend (large but required for sim).
if [[ -f "$SRC/stitched.png" ]]; then
  cp -f "$SRC/stitched.png" "$DEST/stitched.png"
  echo "    copied stitched.png ($(du -h "$DEST/stitched.png" | cut -f1))"
else
  echo "    WARNING: stitched.png not found in source — sim PTZ will fail until provided" >&2
fi

# Marker so we can detect a vendored runtime.
cat > "$DEST/VENDORED.md" <<EOF
Vendored copy of ptz-agent runtime (tools/, msa/, sensors/, stitched.png).
Source: $SRC
Generated by scripts/vendor_ptz_agent.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
Do not edit by hand; re-run the script to refresh.
EOF

echo "==> Done. Verify with: python -m ptz_node doctor"
